apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-23T11:20:25Z"
  labels:
    app: tmt-web
  name: tmt-web
spec:
  containers:
  # Uvicorn
  - image: quay.io/testing-farm/tmt-web:latest
    args:
    - uvicorn
    name: uvicorn
    ports:
    - containerPort: 8000
      hostPort: 8000
    env:
    - name: REDIS_URL
      value: redis://redis:6379
    - name: API_HOSTNAME
      value: http://localhost:8000
  # Celery
  - image: quay.io/testing-farm/tmt-web:latest
    args:
    - celery
    name: celery
    env:
      - name: REDIS_URL
        value: redis://redis:6379
      - name: API_HOSTNAME
        value: http://localhost:8000
  # Redis
  - image: redis:latest
    name: redis
    ports:
      - containerPort: 6379
        hostPort: 6379

